const tokens = {
  colors: {
    background: '#F7F5F0',
    card: '#FFFFFF',
    mutedCard: '#F3F1EB',
    border: '#E7E2D8',
    textPrimary: '#242932',
    textSecondary: '#707986',
    textTertiary: '#9AA3AF',
    success: '#60A879',
    successPressed: '#538F67',
    successSoft: '#ECF7F0',
    destructive: '#D75A4A',
    destructivePressed: '#BE4D3F',
    destructiveSoft: '#FCEDEA',
    warning: '#C28E3E',
    warningSoft: '#FBF3E4',
    pill: '#F4F6F8',
    input: '#FCFBF8',
    disabledBackground: '#ECE9E2',
    disabledText: '#A39B8E',
    iconDefault: '#707986',
    iconMuted: '#A1A9B4',
    tabActive: '#60A879',
    tabInactive: '#98A2B2',
    overlay: 'rgba(22, 27, 34, 0.22)',
  },
  spacing: {
    0: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    9: 36,
    10: 40,
    12: 48,
  },
  radius: {
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    full: 999,
  },
  shadow: {
    card: {
      shadowColor: '#1F2937',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.05,
      shadowRadius: 18,
      elevation: 3,
    },
    soft: {
      shadowColor: '#1F2937',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.035,
      shadowRadius: 14,
      elevation: 2,
    },
    floating: {
      shadowColor: '#1F2937',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.08,
      shadowRadius: 20,
      elevation: 4,
    },
  },
  fontFamily: {
    sans: 'System',
    medium: 'System',
    semibold: 'System',
    bold: 'System',
    target: 'Inter',
  },
  typography: {
    screenTitle: {
      fontSize: 34,
      lineHeight: 40,
      fontWeight: '700',
      letterSpacing: -0.8,
    },
    sectionLabel: {
      fontSize: 11,
      lineHeight: 14,
      fontWeight: '700',
      letterSpacing: 1.1,
    },
    cardEyebrow: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '700',
      letterSpacing: 1,
    },
    kpiValue: {
      fontSize: 44,
      lineHeight: 48,
      fontWeight: '700',
      letterSpacing: -1.4,
    },
    kpiSuffix: {
      fontSize: 17,
      lineHeight: 22,
      fontWeight: '500',
      letterSpacing: -0.2,
    },
    statValue: {
      fontSize: 28,
      lineHeight: 32,
      fontWeight: '700',
      letterSpacing: -0.7,
    },
    statLabel: {
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '500',
      letterSpacing: -0.1,
    },
    body: {
      fontSize: 15,
      lineHeight: 21,
      fontWeight: '400',
      letterSpacing: -0.1,
    },
    bodyMuted: {
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '400',
      letterSpacing: -0.08,
    },
    listTitle: {
      fontSize: 17,
      lineHeight: 22,
      fontWeight: '600',
      letterSpacing: -0.2,
    },
    listMeta: {
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '500',
      letterSpacing: -0.08,
    },
    buttonLabel: {
      fontSize: 16,
      lineHeight: 20,
      fontWeight: '600',
      letterSpacing: -0.15,
    },
    inputLabel: {
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '600',
      letterSpacing: 0,
    },
    tabLabel: {
      fontSize: 12,
      lineHeight: 14,
      fontWeight: '600',
      letterSpacing: -0.04,
    },
  },
};

module.exports = { tokens };
